// 2026 NBA Draft: NBA_2026_2027ロスター完成版.xlsx の「ドラフト2026」シート(行2-61, 60名)から作成した静的データ。
// Excel本体はリポジトリに含めない。更新する場合はこのファイルを直接編集する。
// height_cm / weight_kg が未取得の選手、birthday(元データに存在しない)は null のまま保持しない。

export interface DraftPick {
  round: 1 | 2;
  pickInRound: number;
  overallPick: number;
  playerNameJa: string;
  playerNameEn: string;
  // 既存30チームマスターの英語表記。トレード対象ピックは "TeamA -> TeamB" 形式(指名先・トレード情報)。
  teamDisplay: string;
  // Excel原本のチーム欄。変換できなかった場合は teamDisplay と同じ値になる。
  teamRaw: string;
  position: string | null;
  preDraftTeam: string | null;
  heightCm: number | null;
  weightKg: number | null;
  nationality: string | null;
  // 例: "2026 Rnd 1 Pick 5"。順位・巡目の根拠として保持。
  draftStatus: string;
}

export const DRAFT_2026_PICKS: DraftPick[] = [
  {
    round: 1,
    pickInRound: 1,
    overallPick: 1,
    playerNameJa: "AJ・ディバンサ",
    playerNameEn: "AJ Dybantsa",
    teamDisplay: "Washington Wizards",
    teamRaw: "ワシントン・ウィザーズ",
    position: "F",
    preDraftTeam: "ブリガムヤング大学1年",
    heightCm: 205,
    weightKg: 98,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 1",
  },
  {
    round: 1,
    pickInRound: 2,
    overallPick: 2,
    playerNameJa: "ダリン・ピーターソン",
    playerNameEn: "Darryn Peterson",
    teamDisplay: "Utah Jazz",
    teamRaw: "ユタ・ジャズ",
    position: null,
    preDraftTeam: "カンザス大学1年",
    heightCm: 195,
    weightKg: 90,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 2",
  },
  {
    round: 1,
    pickInRound: 3,
    overallPick: 3,
    playerNameJa: "キャメロン・ブーザー",
    playerNameEn: "Cameron Boozer",
    teamDisplay: "Memphis Grizzlies",
    teamRaw: "メンフィス・グリズリーズ",
    position: "F/C",
    preDraftTeam: "デューク大学1年",
    heightCm: 203,
    weightKg: 114,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 3",
  },
  {
    round: 1,
    pickInRound: 4,
    overallPick: 4,
    playerNameJa: "ケイレブ・ウィルソン",
    playerNameEn: "Caleb Wilson",
    teamDisplay: "Chicago Bulls",
    teamRaw: "シカゴ・ブルズ",
    position: "F",
    preDraftTeam: "ノースカロライナ大学1年",
    heightCm: 205,
    weightKg: 95,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 4",
  },
  {
    round: 1,
    pickInRound: 5,
    overallPick: 5,
    playerNameJa: "キートン・ワグラー",
    playerNameEn: "Keaton Wagler",
    teamDisplay: "LA Clippers",
    teamRaw: "ロサンゼルス・クリッパーズ",
    position: "G",
    preDraftTeam: "イリノイ大学1年",
    heightCm: 195,
    weightKg: 85,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 5",
  },
  {
    round: 1,
    pickInRound: 6,
    overallPick: 6,
    playerNameJa: "マイケル・ブラウンJr.",
    playerNameEn: "Mikel Brown Jr.",
    teamDisplay: "Brooklyn Nets",
    teamRaw: "ブルックリン・ネッツ",
    position: "G",
    preDraftTeam: "ルイビル大学1年",
    heightCm: 195,
    weightKg: 81,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 6",
  },
  {
    round: 1,
    pickInRound: 7,
    overallPick: 7,
    playerNameJa: "ダリアス・エイカフJr.",
    playerNameEn: "Darius Acuff Jr.",
    teamDisplay: "Sacramento Kings",
    teamRaw: "サクラメント・キングス",
    position: "G",
    preDraftTeam: "アーカンソー大学1年",
    heightCm: 187,
    weightKg: 84,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 7",
  },
  {
    round: 1,
    pickInRound: 8,
    overallPick: 8,
    playerNameJa: "キングストン・フレミングス",
    playerNameEn: "Kingston Flemings",
    teamDisplay: "Atlanta Hawks",
    teamRaw: "アトランタ・ホークス",
    position: "G",
    preDraftTeam: "ヒューストン大学1年",
    heightCm: 190,
    weightKg: 83,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 8",
  },
  {
    round: 1,
    pickInRound: 9,
    overallPick: 9,
    playerNameJa: "モレズ・ジョンソンJr.",
    playerNameEn: "Morez Johnson Jr.",
    teamDisplay: "Dallas Mavericks",
    teamRaw: "ダラス・マーベリックス",
    position: "F/C",
    preDraftTeam: "ミシガン大学2年",
    heightCm: 205,
    weightKg: 113,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 9",
  },
  {
    round: 1,
    pickInRound: 10,
    overallPick: 10,
    playerNameJa: "ブレイデン・バリーズ",
    playerNameEn: "Brayden Burries",
    teamDisplay: "Milwaukee Bucks",
    teamRaw: "ミルウォーキー・バックス",
    position: "G",
    preDraftTeam: "アリゾナ大学1年",
    heightCm: 193,
    weightKg: 97,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 10",
  },
  {
    round: 1,
    pickInRound: 11,
    overallPick: 11,
    playerNameJa: "ヤクセル・レンデボーグ",
    playerNameEn: "Yaxel Lendeborg",
    teamDisplay: "Golden State Warriors",
    teamRaw: "ゴールデンステイト・ウォリアーズ",
    position: "F",
    preDraftTeam: "ミシガン大学4年",
    heightCm: 205,
    weightKg: 109,
    nationality: "Dominican Republic/United States",
    draftStatus: "2026 Rnd 1 Pick 11",
  },
  {
    round: 1,
    pickInRound: 12,
    overallPick: 12,
    playerNameJa: "アデイ・マーラ",
    playerNameEn: "Aday Mara",
    teamDisplay: "Oklahoma City Thunder",
    teamRaw: "オクラホマシティ・サンダー",
    position: "C",
    preDraftTeam: "ミシガン大学3年",
    heightCm: 221,
    weightKg: 117,
    nationality: "Spain",
    draftStatus: "2026 Rnd 1 Pick 12",
  },
  {
    round: 1,
    pickInRound: 13,
    overallPick: 13,
    playerNameJa: "ネイト・エイメント",
    playerNameEn: "Nate Ament",
    teamDisplay: "Miami Heat",
    teamRaw: "マイアミ・ヒート",
    position: "F",
    preDraftTeam: "テネシー大学1年",
    heightCm: 208,
    weightKg: 95,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 13",
  },
  {
    round: 1,
    pickInRound: 14,
    overallPick: 14,
    playerNameJa: "ハンネス・スタインバック",
    playerNameEn: "Hannes Steinbach",
    teamDisplay: "Charlotte Hornets",
    teamRaw: "シャーロット・ホーネッツ",
    position: "F/C",
    preDraftTeam: "ワシントン大学1年",
    heightCm: 208,
    weightKg: 112,
    nationality: "Germany",
    draftStatus: "2026 Rnd 1 Pick 14",
  },
  {
    round: 1,
    pickInRound: 15,
    overallPick: 15,
    playerNameJa: "デイリン・スウェイン",
    playerNameEn: "Dailyn Swain",
    teamDisplay: "Chicago Bulls",
    teamRaw: "シカゴ・ブルズ",
    position: "F",
    preDraftTeam: "テキサス大学3年",
    heightCm: 200,
    weightKg: 95,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 15",
  },
  {
    round: 1,
    pickInRound: 16,
    overallPick: 16,
    playerNameJa: "ベネット・スターツ",
    playerNameEn: "Bennett Stirtz",
    teamDisplay: "Memphis Grizzlies",
    teamRaw: "メンフィス・グリズリーズ",
    position: "G",
    preDraftTeam: "アイオワ大学3年",
    heightCm: 190,
    weightKg: 84,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 16",
  },
  {
    round: 1,
    pickInRound: 17,
    overallPick: 17,
    playerNameJa: "エブカ・オコリエ",
    playerNameEn: "Ebuka Okorie",
    teamDisplay: "Oklahoma City Thunder",
    teamRaw: "オクラホマシティ・サンダー",
    position: "G",
    preDraftTeam: "スタンフォード大学1年",
    heightCm: 185,
    weightKg: 84,
    nationality: "U.K",
    draftStatus: "2026 Rnd 1 Pick 17",
  },
  {
    round: 1,
    pickInRound: 18,
    overallPick: 18,
    playerNameJa: "クリスチャン・アンダーソン",
    playerNameEn: "Christian Anderson",
    teamDisplay: "Charlotte Hornets",
    teamRaw: "シャーロット・ホーネッツ",
    position: "G",
    preDraftTeam: "テキサス工科大学2年",
    heightCm: 185,
    weightKg: 81,
    nationality: "Germany/United States",
    draftStatus: "2026 Rnd 1 Pick 18",
  },
  {
    round: 1,
    pickInRound: 19,
    overallPick: 19,
    playerNameJa: "アレン・グレイブス",
    playerNameEn: "Allen Graves",
    teamDisplay: "Oklahoma City Thunder",
    teamRaw: "オクラホマシティ・サンダー",
    position: "F",
    preDraftTeam: "サンタクララ大学1年",
    heightCm: 203,
    weightKg: 102,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 19",
  },
  {
    round: 1,
    pickInRound: 20,
    overallPick: 20,
    playerNameJa: "ジェイデン・クエインタンス",
    playerNameEn: "Jayden Quaintance",
    teamDisplay: "San Antonio Spurs",
    teamRaw: "サンアントニオ・スパーズ",
    position: "F/C",
    preDraftTeam: "ケンタッキー大学2年",
    heightCm: 205,
    weightKg: 114,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 20",
  },
  {
    round: 1,
    pickInRound: 21,
    overallPick: 21,
    playerNameJa: "カリム・ロペス",
    playerNameEn: "Karim Lopez",
    teamDisplay: "Detroit Pistons",
    teamRaw: "デトロイト・ピストンズ",
    position: "F",
    preDraftTeam: "ニュージーランド・ブレイカーズ（豪州NBL）",
    heightCm: 203,
    weightKg: 100,
    nationality: "Mexico",
    draftStatus: "2026 Rnd 1 Pick 21",
  },
  {
    round: 1,
    pickInRound: 22,
    overallPick: 22,
    playerNameJa: "ラバロン・ファイロンJr.",
    playerNameEn: "Labaron Philon Jr.",
    teamDisplay: "Philadelphia 76ers",
    teamRaw: "フィラデルフィア・76ers",
    position: "G",
    preDraftTeam: "アラバマ大学2年",
    heightCm: 190,
    weightKg: 79,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 22",
  },
  {
    round: 1,
    pickInRound: 23,
    overallPick: 23,
    playerNameJa: "ズビー・エジオフォ",
    playerNameEn: "Zuby Ejiofor",
    teamDisplay: "Atlanta Hawks",
    teamRaw: "アトランタ・ホークス",
    position: "F/C",
    preDraftTeam: "セント・ジョーンズ大学4年",
    heightCm: 203,
    weightKg: 111,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 23",
  },
  {
    round: 1,
    pickInRound: 24,
    overallPick: 24,
    playerNameJa: "キャメロン・カー",
    playerNameEn: "Cameron Carr",
    teamDisplay: "New York Knicks",
    teamRaw: "ニューヨーク・ニックス",
    position: "G",
    preDraftTeam: "ベイラー大学2年",
    heightCm: 195,
    weightKg: 83,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 24",
  },
  {
    round: 1,
    pickInRound: 25,
    overallPick: 25,
    playerNameJa: "セルヒオ・デ・ラレア",
    playerNameEn: "Sergio De Larrea",
    teamDisplay: "Los Angeles Lakers",
    teamRaw: "ロサンゼルス・レイカーズ",
    position: "G",
    preDraftTeam: "バレンシア（スペイン）",
    heightCm: 198,
    weightKg: 92,
    nationality: "Spain",
    draftStatus: "2026 Rnd 1 Pick 25",
  },
  {
    round: 1,
    pickInRound: 26,
    overallPick: 26,
    playerNameJa: "タリス・リードJr.",
    playerNameEn: "Tarris Reed Jr.",
    teamDisplay: "Denver Nuggets",
    teamRaw: "デンバー・ナゲッツ",
    position: "C",
    preDraftTeam: "コネチカット大学4年",
    heightCm: 208,
    weightKg: 118,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 26",
  },
  {
    round: 1,
    pickInRound: 27,
    overallPick: 27,
    playerNameJa: "クリス・セナックJr.",
    playerNameEn: "Chris Cenac Jr.",
    teamDisplay: "Boston Celtics",
    teamRaw: "ボストン・セルティックス",
    position: "F/C",
    preDraftTeam: "ヒューストン大学1年",
    heightCm: 210,
    weightKg: 108,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 27",
  },
  {
    round: 1,
    pickInRound: 28,
    overallPick: 28,
    playerNameJa: "ジョシュア・ジェファーソン",
    playerNameEn: "Joshua Jefferson",
    teamDisplay: "Minnesota Timberwolves",
    teamRaw: "ミネソタ・ティンバーウルブズ",
    position: "F",
    preDraftTeam: "アイオワ州立大学4年",
    heightCm: 203,
    weightKg: 111,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 28",
  },
  {
    round: 1,
    pickInRound: 29,
    overallPick: 29,
    playerNameJa: "アレックス・カラバン",
    playerNameEn: "Alex Karaban",
    teamDisplay: "Cleveland Cavaliers",
    teamRaw: "クリーブランド・キャバリアーズ",
    position: "F",
    preDraftTeam: "コネチカット大学4年",
    heightCm: 200,
    weightKg: 102,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 29",
  },
  {
    round: 1,
    pickInRound: 30,
    overallPick: 30,
    playerNameJa: "コア・ピート",
    playerNameEn: "Koa Peat",
    teamDisplay: "Dallas Mavericks",
    teamRaw: "ダラス・マーベリックス",
    position: "F",
    preDraftTeam: "アリゾナ大学1年",
    heightCm: 200,
    weightKg: 111,
    nationality: "United States",
    draftStatus: "2026 Rnd 1 Pick 30",
  },
  {
    round: 2,
    pickInRound: 1,
    overallPick: 31,
    playerNameJa: "ブルース・ソーントン",
    playerNameEn: "Bruce Thornton",
    teamDisplay: "ヒューストン・ロケッツ（ニックス経由）",
    teamRaw: "ヒューストン・ロケッツ（ニックス経由）",
    position: "G",
    preDraftTeam: "オハイオ大学4年",
    heightCm: 183,
    weightKg: 101,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 1",
  },
  {
    round: 2,
    pickInRound: 2,
    overallPick: 32,
    playerNameJa: "リッチー・サンダース",
    playerNameEn: "Richie Saunders",
    teamDisplay: "Memphis Grizzlies",
    teamRaw: "メンフィス・グリズリーズ",
    position: "G",
    preDraftTeam: "BYU",
    heightCm: 196,
    weightKg: 93,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 2",
  },
  {
    round: 2,
    pickInRound: 3,
    overallPick: 33,
    playerNameJa: "アイザイア・エバンス",
    playerNameEn: "Isaiah Evans",
    teamDisplay: "Brooklyn Nets",
    teamRaw: "ブルックリン・ネッツ",
    position: "G",
    preDraftTeam: "デューク大学2年生",
    heightCm: 198,
    weightKg: 84,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 3",
  },
  {
    round: 2,
    pickInRound: 4,
    overallPick: 34,
    playerNameJa: "メリーク・トーマス",
    playerNameEn: "Meleek Thomas",
    teamDisplay: "Sacramento Kings → Cleveland Cavaliers",
    teamRaw: "サクラメント・キングス→クリーブランド・キャバリアーズへトレード",
    position: "G・F",
    preDraftTeam: "アーカンソー大学1年生",
    heightCm: 191,
    weightKg: 86,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 4",
  },
  {
    round: 2,
    pickInRound: 5,
    overallPick: 35,
    playerNameJa: "トレボン・ブラジル",
    playerNameEn: "Trevon Brazile",
    teamDisplay: "San Antonio Spurs → Denver Nuggets",
    teamRaw: "サンアントニオ・スパーズ→デンバー・ナゲッツへトレード",
    position: "F",
    preDraftTeam: "アーカンソー大学4年生",
    heightCm: 208,
    weightKg: 103,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 5",
  },
  {
    round: 2,
    pickInRound: 6,
    overallPick: 36,
    playerNameJa: "ババ・ミラー",
    playerNameEn: "Baba Miller",
    teamDisplay: "LA Clippers",
    teamRaw: "ロサンゼルス・クリッパーズ",
    position: "F",
    preDraftTeam: "シンシナティ大学4年生",
    heightCm: 211,
    weightKg: 94,
    nationality: "Spain",
    draftStatus: "2026 Rnd 2 Pick 6",
  },
  {
    round: 2,
    pickInRound: 7,
    overallPick: 37,
    playerNameJa: "ライアン・コンウェル",
    playerNameEn: "Ryan Conwell",
    teamDisplay: "Oklahoma City Thunder",
    teamRaw: "オクラホマシティ・サンダー",
    position: "G",
    preDraftTeam: "ルイビル大学4年生",
    heightCm: 193,
    weightKg: 98,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 7",
  },
  {
    round: 2,
    pickInRound: 8,
    overallPick: 38,
    playerNameJa: "ブレイデン・スミス",
    playerNameEn: "Braden Smith",
    teamDisplay: "Chicago Bulls → Indiana Pacers",
    teamRaw: "シカゴ・ブルズ→インディアナ・ペイサーズへトレード",
    position: "G",
    preDraftTeam: "パデュー大学4年生",
    heightCm: 178,
    weightKg: 76,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 8",
  },
  {
    round: 2,
    pickInRound: 9,
    overallPick: 39,
    playerNameJa: "ジャック・カイル",
    playerNameEn: "Jack Kayil",
    teamDisplay: "Houston Rockets → New York Knicks",
    teamRaw: "ヒューストン・ロケッツ→ニューヨーク・ニックスへトレード",
    position: "G",
    preDraftTeam: "アルバ・ベルリン（ドイツ）",
    heightCm: 196,
    weightKg: 84,
    nationality: "Germany",
    draftStatus: "2026 Rnd 2 Pick 9",
  },
  {
    round: 2,
    pickInRound: 10,
    overallPick: 40,
    playerNameJa: "ディロン・ミッチェル",
    playerNameEn: "Dillon Mitchell",
    teamDisplay: "Boston Celtics",
    teamRaw: "ボストン・セルティックス",
    position: "F",
    preDraftTeam: "セントジョーンズ大学4年生",
    heightCm: 203,
    weightKg: 95,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 10",
  },
  {
    round: 2,
    pickInRound: 11,
    overallPick: 41,
    playerNameJa: "オテガ・オウェ",
    playerNameEn: "Otega Oweh",
    teamDisplay: "Miami Heat → Oklahoma City Thunder",
    teamRaw: "マイアミ・ヒート→オクラホマシティ・サンダーへトレード",
    position: "G",
    preDraftTeam: "ケンタッキー大学4年生",
    heightCm: 196,
    weightKg: 95,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 11",
  },
  {
    round: 2,
    pickInRound: 12,
    overallPick: 42,
    playerNameJa: "ジャコビ・ギレスピー",
    playerNameEn: "Ja’Kobi Gillespie",
    teamDisplay: "San Antonio Spurs",
    teamRaw: "サンアントニオ・スパーズ",
    position: "G",
    preDraftTeam: "テネシー大学4年生",
    heightCm: 183,
    weightKg: 83,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 12",
  },
  {
    round: 2,
    pickInRound: 13,
    overallPick: 43,
    playerNameJa: "タイラー・ビロドウ",
    playerNameEn: "Tyler Bilodeau",
    teamDisplay: "Brooklyn Nets",
    teamRaw: "ブルックリン・ネッツ",
    position: "F",
    preDraftTeam: "UCLA4年生",
    heightCm: 203,
    weightKg: 103,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 13",
  },
  {
    round: 2,
    pickInRound: 14,
    overallPick: 44,
    playerNameJa: "マリク・ブラウン",
    playerNameEn: "Maliq Brown",
    teamDisplay: "San Antonio Spurs",
    teamRaw: "サンアントニオ・スパーズ",
    position: "F",
    preDraftTeam: "デューク大学4年生",
    heightCm: 203,
    weightKg: 98,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 14",
  },
  {
    round: 2,
    pickInRound: 15,
    overallPick: 45,
    playerNameJa: "エマニュエル・シャープ",
    playerNameEn: "Emanuel Sharp",
    teamDisplay: "Sacramento Kings",
    teamRaw: "サクラメント・キングス",
    position: "G",
    preDraftTeam: "ヒューストン大学4年生",
    heightCm: 191,
    weightKg: 94,
    nationality: "Israel/United States",
    draftStatus: "2026 Rnd 2 Pick 15",
  },
  {
    round: 2,
    pickInRound: 16,
    overallPick: 46,
    playerNameJa: "フェリックス・オパラ",
    playerNameEn: "Felix Okpara",
    teamDisplay: "Orlando Magic → Washington Wizards",
    teamRaw: "オーランド・マジック→ワシントン・ウィザーズへトレード",
    position: "F・C",
    preDraftTeam: "テネシー大学4年生",
    heightCm: 208,
    weightKg: 108,
    nationality: "Nigeria",
    draftStatus: "2026 Rnd 2 Pick 16",
  },
  {
    round: 2,
    pickInRound: 17,
    overallPick: 47,
    playerNameJa: "タイラー・ニッケル",
    playerNameEn: "Tyler Nickel",
    teamDisplay: "Phoenix Suns → New York Knicks",
    teamRaw: "フェニックス・サンズ→ニューヨーク・ニックスへトレード",
    position: "F・G",
    preDraftTeam: "ヴァンダービルド大学4年生",
    heightCm: 203,
    weightKg: 98,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 17",
  },
  {
    round: 2,
    pickInRound: 18,
    overallPick: 48,
    playerNameJa: "トビ・ラワル",
    playerNameEn: "Tobi Lawal",
    teamDisplay: "Dallas Mavericks",
    teamRaw: "ダラス・マーベリックス",
    position: "F",
    preDraftTeam: "バージニア工科大学4年生",
    heightCm: 203,
    weightKg: 98,
    nationality: "U.K",
    draftStatus: "2026 Rnd 2 Pick 18",
  },
  {
    round: 2,
    pickInRound: 19,
    overallPick: 49,
    playerNameJa: "ブライス・ホプキンズ",
    playerNameEn: "Bryce Hopkins",
    teamDisplay: "Denver Nuggets",
    teamRaw: "デンバー・ナゲッツ",
    position: "F",
    preDraftTeam: "セントジョーンズ大学4年生",
    heightCm: 198,
    weightKg: 99,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 19",
  },
  {
    round: 2,
    pickInRound: 20,
    overallPick: 50,
    playerNameJa: "ジェイデン・ブラッドリー",
    playerNameEn: "Jaden Bradley",
    teamDisplay: "Toronto Raptors → Orlando Magic",
    teamRaw: "トロント・ラプターズ→オーランド・マジックへトレード",
    position: "C",
    preDraftTeam: "サウスフロリダ大学4年生",
    heightCm: 191,
    weightKg: 93,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 20",
  },
  {
    round: 2,
    pickInRound: 21,
    overallPick: 51,
    playerNameJa: "イザイア・ネルソン",
    playerNameEn: "Izaiyah Nelson",
    teamDisplay: "Washington Wizards",
    teamRaw: "ワシントン・ウィザーズ",
    position: "G",
    preDraftTeam: "アリゾナ大学4年生",
    heightCm: 203,
    weightKg: 99,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 21",
  },
  {
    round: 2,
    pickInRound: 22,
    overallPick: 52,
    playerNameJa: "アンリ・ヴィーザール",
    playerNameEn: "Henri Veesaar",
    teamDisplay: "LA Clippers → Atlanta Hawks",
    teamRaw: "ロサンゼルス・クリッパーズ→アトランタ・ホークスへトレード",
    position: "G",
    preDraftTeam: "ノースカロライナ大学3年生",
    heightCm: 203,
    weightKg: 99,
    nationality: "Estonia",
    draftStatus: "2026 Rnd 2 Pick 22",
  },
  {
    round: 2,
    pickInRound: 23,
    overallPick: 53,
    playerNameJa: "ウゴンナ・オニエンソ",
    playerNameEn: "Ugonna Onyenso",
    teamDisplay: "Houston Rockets → Detroit Pistons",
    teamRaw: "ヒューストン・ロケッツ→デトロイト・ピストンズへトレード",
    position: "C",
    preDraftTeam: "バージニア大学4年生",
    heightCm: 211,
    weightKg: 108,
    nationality: "Nigeria",
    draftStatus: "2026 Rnd 2 Pick 23",
  },
  {
    round: 2,
    pickInRound: 24,
    overallPick: 54,
    playerNameJa: "レイジャ・ジョーンズ",
    playerNameEn: "Lajae Jones",
    teamDisplay: "Golden State Warriors",
    teamRaw: "ゴールデンステイト・ウォリアーズ",
    position: "G",
    preDraftTeam: "フロリダ大学4年生",
    heightCm: null,
    weightKg: null,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 24",
  },
  {
    round: 2,
    pickInRound: 25,
    overallPick: 55,
    playerNameJa: "ニック・マルティネッリ",
    playerNameEn: "Nick Martinelli",
    teamDisplay: "New York Knicks → LA Clippers",
    teamRaw: "ニューヨーク・ニックス→ロサンゼルス・クリッパーズへトレード",
    position: "F",
    preDraftTeam: "ノースウェスタン大学4年生",
    heightCm: 201,
    weightKg: 102,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 25",
  },
  {
    round: 2,
    pickInRound: 26,
    overallPick: 56,
    playerNameJa: "フセヴォロド・イシチェンコ",
    playerNameEn: "Vsevolod Ishchenko",
    teamDisplay: "Chicago Bulls → Dallas Mavericks",
    teamRaw: "シカゴ・ブルズ→ダラス・マーベリックスへトレード",
    position: "G",
    preDraftTeam: "ロコモティフ・クバン（ロシア）",
    heightCm: 203,
    weightKg: 99,
    nationality: "Russia",
    draftStatus: "2026 Rnd 2 Pick 26",
  },
  {
    round: 2,
    pickInRound: 27,
    overallPick: 57,
    playerNameJa: "ナルシス・ノイ",
    playerNameEn: "Narcisse Ngoy",
    teamDisplay: "Atlanta Hawks → LA Clippers",
    teamRaw: "アトランタ・ホークス→ロサンゼルス・クリッパーズへトレード",
    position: "C",
    preDraftTeam: "ポワティエ（フランス）",
    heightCm: 213,
    weightKg: 107,
    nationality: "France",
    draftStatus: "2026 Rnd 2 Pick 27",
  },
  {
    round: 2,
    pickInRound: 28,
    overallPick: 58,
    playerNameJa: "ジャロン・ピエール・ジュニア",
    playerNameEn: "Jaron Pierre Jr.",
    teamDisplay: "New Orleans Pelicans",
    teamRaw: "ニューオーリンズ・ペリカンズ",
    position: "G・F",
    preDraftTeam: "南メソジスト大学4年生",
    heightCm: 198,
    weightKg: 95,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 28",
  },
  {
    round: 2,
    pickInRound: 29,
    overallPick: 59,
    playerNameJa: "トレイ・カウフマン・レン",
    playerNameEn: "Trey Kaufman-Renn",
    teamDisplay: "Minnesota Timberwolves",
    teamRaw: "ミネソタ・ティンバーウルブズ",
    position: "F",
    preDraftTeam: "パデュー大学4年生",
    heightCm: 206,
    weightKg: 109,
    nationality: "United States",
    draftStatus: "2026 Rnd 2 Pick 29",
  },
  {
    round: 2,
    pickInRound: 30,
    overallPick: 60,
    playerNameJa: "マリク・ルイス",
    playerNameEn: "Malique Lewis",
    teamDisplay: "Washington Wizards → Milwaukee Bucks",
    teamRaw: "ワシントン・ウィザーズ→ミルウォーキー・バックス",
    position: "F",
    preDraftTeam: "サウスイースト・メルボルン（オーストラリア）",
    heightCm: 203,
    weightKg: 88,
    nationality: "Republic of Trinidad and Tobago",
    draftStatus: "2026 Rnd 2 Pick 30",
  },
];
